### ISSUE TITLE
Awesome Project

### ISSUE THREAD

**Issue by polijan** [benchmarko/CPCBasic#1]
Hi! This is not an actual issue :) Sorry, I didn't know how to comment otherwise and I just wanted to say "Thank You" for this project. CPCBasic is fun and awesome. Amstrad CPCs were great and writing stuff in Basic has always been awesome (and easier and more fun than Javascript for small programs). Now that machine are so fast, it feels even better :+1: 

Here's one tiny program for you:

```
1 ' CIRCLE WRITER... by "COMTEC", found in an old CPC Magazine
2 ' and very slightly modified.   Very slow on a real CPC, but
3 ' now ultra fast with *CPC Basic* on a modern computer.  ;-D
5 ' 
6 text$="CPC BASIC is SUPER AWESOME "
7 '
10 MODE 1:mo=16:INK 0,0:INK 1,26:INK 2,13:BORDER 0:PAPER 0:PEN 1
20 le=120:he=120:th=64:x=320:y=200:col=1
30 length=LEN(text$):steps=360/length:sti=steps/mo:thi=th/mo
40 PEN 2:LOCATE 1,25:PRINT text$
50 FOR nu=0 TO length-1
60 FOR i=0 TO mo-1:FOR o=0 TO mo-1
70 IF TEST((nu*mo)+i,o)<>0 THEN 90
80 NEXT o,i,nu
81 INK 2,0:CALL &BB18:PEN 1:END
90 de=-(nu*steps)-sti*i-180:th=thi*o:DEG
100 plot x+(le+th)*COS(de),y+(he+th)*SIN(de),col:GOTO 80
```

Thanks! :100:

**Comment by benchmarko** [comment]
Thank you for the great feedback!

It took some time until the next update but now the little program is in apps:
https://benchmarko.github.io/CPCBasic/cpcbasic.html?database=apps&example=demo/circlewr
...and with an extension for different modes also in examples:
https://benchmarko.github.io/CPCBasic/cpcbasic.html?example=circlewr

And the issue with WHILE INKEY$<>"":WEND:CALL &BB18 (did not wait for the key) is also fixed.

Have fun!
